language: emacs-lisp
sudo: false
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask install
env:
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
script:
  - emacs --version
  - cask build
  - cask clean-elc
  - cask exec ert-runner -l test/ert-helper.el test/*-tests.el
  - cask emacs --batch -Q -l package-lint.el -f package-lint-batch-and-exit lisp/*.el
notifications:
    webhooks:
        urls:
          - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGpvaG5zb24lM0FtYXRyaXgub3JnLyUyMVpSbGVnVEFCTHBTQmJ2c01tTiUzQW1hdHJpeC5vcmc"
        on_success: always # always|never|change
        on_failure: always
        on_start: never
